---

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if a supported cloud has been specified
      fail:
        msg: |-
          You must specify a cloud from the options below:

            - aws
            - aws_govcloud
            - azure
      tags: [always]
      when: cloud not in ['aws', 'aws_govcloud', 'azure']

- hosts: localhost
  tasks:
    - name: Create infrastructure in AWS
      include_role:
        name: infrastructure
        tasks_from: aws_create
      tags: [infrastructure]
      when: cloud == 'aws'

    - name: Create infrastructure in AWS GovCloud
      include_role:
        name: infrastructure
        tasks_from: aws_govcloud_create
      tags: [infrastructure]
      when: cloud == 'aws_govcloud'

    - name: Create infrastructure in Azure
      include_role:
        name: infrastructure
        tasks_from: azure_create
      tags: [infrastructure]
      when: cloud == 'azure'

- hosts: bastion
  tasks:
    - import_role:
        name: host_prep
        tasks_from: bastion
      tags: [prep]

    - import_role:
        name: openshift_install
      tags: [install]

    - import_role:
        name: post_config
      tags: [config]

    - import_role:
        name: output_cluster_info
      tags: [output]
