---
# tasks file for prep_bastion

- block:
    - name: Create SSH keys
      openssh_keypair:
        path: ~/.ssh/id_rsa
      register: r_prep_bastion_create_ssh_keys

    - name: Set the SSH public key fact
      set_fact:
        ssh_public_key: "{{ r_prep_bastion_create_ssh_keys.public_key | trim }}"
  when: ssh_public_key is undefined

- name: Add additional authorized keys
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item }}"
    state: present
  loop: "{{ additional_authorized_keys }}"

- name: Create MOTD
  template:
    src: bastion_motd.j2
    dest: /etc/motd
  become: yes

- name: Add OpenShift nodes to hosts file
  blockinfile:
    path: /etc/hosts
    block: |
      {% for master in groups.masters %}
      {{ hostvars[master].ip_address }}  master{{ loop.index0 }}
      {% endfor %}
      {%- for worker in groups.workers %}
      {{ hostvars[worker].ip_address }}  worker{{ loop.index0 }}
      {% endfor %}
  become: yes

- name: Set KUBECONFIG in .bashrc
  lineinfile:
    path: ~/.bashrc
    regexp: "^export KUBECONFIG="
    line: export KUBECONFIG=$HOME/ocp4/auth/kubeconfig

- name: Install required packages
  yum:
    name:
      - bind-utils
      - git
      - httpd
      - python3
      - python3-pip
      - screen
      - unzip
      - vim
      - wget
    state: present
  become: yes

- name: Install k8s module dependencies
  pip:
    name:
      - openshift
      - PyYAML
    executable: pip3
    state: present
  become: yes

- import_tasks: openshift_installer.yml

- import_tasks: helm.yml

- name: Start and enable httpd
  service:
    name: httpd
    state: started
    enabled: yes
  become: yes
